# Generated by Django 5.2.9 on 2026-01-13 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertastock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'ordering': ['-creado_en']},
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='inventario__codigo_d18360_idx',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='inventario__stock_a_d10457_idx',
        ),
        migrations.RenameField(
            model_name='alertastock',
            old_name='fecha_alerta',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='alertastock',
            name='fecha_resolucion',
        ),
        migrations.RemoveField(
            model_name='alertastock',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='alertastock',
            name='resuelta',
        ),
        migrations.RemoveField(
            model_name='alertastock',
            name='stock_actual',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='documento_referencia',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_maximo',
        ),
        migrations.AddField(
            model_name='alertastock',
            name='mensaje',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alertastock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad a mover o nuevo stock si es ajuste', max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo para compras', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('COMPRA', 'Compra / Entrada'), ('CONSUMO', 'Consumo Interno'), ('AJUSTE', 'Ajuste de Inventario')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('UND', 'Unidad'), ('KG', 'Kilogramo'), ('L', 'Litro'), ('ML', 'Mililitro'), ('GR', 'Gramo'), ('CAJA', 'Caja'), ('PAQUETE', 'Paquete'), ('GALON', 'Galón'), ('BIDON', 'Bidón')], max_length=20),
        ),
    ]
