# Generated by Django 5.2.9 on 2026-02-18 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_ticket_dias_entrega_and_more'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajasesion',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_sesion', to='core.sede'),
        ),
    ]
