# Generated by Django 5.2.9 on 2026-02-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_add_sede_to_cajasesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopagoconfig',
            name='codigo_metodo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('YAPE', 'Yape'), ('PLIN', 'Plin')], max_length=20),
        ),
    ]
