# Generated by Django 5.2.9 on 2026-01-05 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_cajasesion_movimientocaja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cajasesion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movimientocaja',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='pagos_pago_numero__d22581_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='pagos_pago_ticket__3103f5_idx',
        ),
        migrations.RenameField(
            model_name='cajasesion',
            old_name='comentario_cierre',
            new_name='comentarios',
        ),
        migrations.RenameField(
            model_name='cajasesion',
            old_name='monto_final_real',
            new_name='monto_real',
        ),
        migrations.RemoveField(
            model_name='cajasesion',
            name='monto_final_sistema',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='notas',
        ),
        migrations.AddField(
            model_name='cajasesion',
            name='diferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cajasesion',
            name='monto_sistema',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_ticket', to='pagos.cajasesion'),
        ),
        migrations.AlterField(
            model_name='cajasesion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_extra', to='pagos.cajasesion'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='categoria',
            field=models.CharField(default='GENERAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso/Gasto')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='PAGADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TRANSFERENCIA', 'Transferencia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='numero_pago',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
