# Generated by Django 5.2.9 on 2026-01-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_cajasesion_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cajasesion',
            old_name='monto_real',
            new_name='monto_final_real',
        ),
        migrations.RenameField(
            model_name='cajasesion',
            old_name='monto_sistema',
            new_name='monto_final_sistema',
        ),
        migrations.AddField(
            model_name='cajasesion',
            name='detalle_apertura',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='cajasesion',
            name='detalle_cierre',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20),
        ),
    ]
