# Generated by Django 5.2.9 on 2026-01-15 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Negocio')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_empresas/', verbose_name='Logo')),
                ('ruc', models.CharField(max_length=20, unique=True, verbose_name='RUC / ID Fiscal')),
                ('direccion_fiscal', models.TextField(blank=True, verbose_name='Dirección Fiscal')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('zona_horaria', models.CharField(default='America/Lima', max_length=50, verbose_name='Zona Horaria')),
                ('moneda', models.CharField(default='PEN', max_length=3, verbose_name='Moneda (ISO)')),
                ('plan', models.CharField(choices=[('FREE', 'Plan Gratuito / Prueba'), ('PRO', 'Plan Profesional'), ('ENTERPRISE', 'Plan Empresarial')], default='FREE', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField(verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido (Falta de pago)'), ('INACTIVO', 'Inactivo (Baja)')], default='ACTIVO', max_length=20)),
                ('stock_minimo_global', models.PositiveIntegerField(default=10, verbose_name='Alerta Stock Mínimo Global')),
                ('notif_email_activas', models.BooleanField(default=True, verbose_name='Activar Email')),
                ('notif_whatsapp_activas', models.BooleanField(default=False, verbose_name='Activar WhatsApp')),
                ('notif_sms_activas', models.BooleanField(default=False, verbose_name='Activar SMS')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('eliminado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la sede')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código Interno')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('horario_apertura', models.TimeField(verbose_name='Horario de apertura')),
                ('horario_cierre', models.TimeField(verbose_name='Horario de cierre')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
    ]
