# Generated by Django 5.2.9 on 2026-03-26 04:04

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Negocio')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_empresas/', verbose_name='Logo')),
                ('ruc', models.CharField(max_length=20, unique=True, verbose_name='RUC / ID Fiscal')),
                ('direccion_fiscal', models.TextField(blank=True, verbose_name='Dirección Fiscal')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('zona_horaria', models.CharField(default='America/Lima', max_length=50, verbose_name='Zona Horaria')),
                ('moneda', models.CharField(default='PEN', max_length=3, verbose_name='Moneda (ISO)')),
                ('plan', models.CharField(choices=[('DEMO', 'Prueba de 7 días'), ('MENSUAL', 'Suscripción Mensual')], default='DEMO', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField(verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido (Falta de pago)'), ('INACTIVO', 'Inactivo (Baja)')], default='ACTIVO', max_length=20)),
                ('ticket_prefijo', models.CharField(default='TK-', max_length=10, verbose_name='Prefijo del Ticket')),
                ('ticket_mensaje_pie', models.TextField(blank=True, verbose_name='Mensaje al pie del ticket')),
                ('ticket_servicios_descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción Inline de Servicios')),
                ('ticket_disclaimer', models.TextField(blank=True, verbose_name='Disclaimer del Ticket')),
                ('ticket_logo', models.ImageField(blank=True, null=True, upload_to='logos_tickets/', verbose_name='Logo del Ticket')),
                ('stock_minimo_global', models.PositiveIntegerField(default=10, verbose_name='Alerta Stock Mínimo Global')),
                ('notif_email_activas', models.BooleanField(default=False, verbose_name='Activar Notificaciones Email')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=100, verbose_name='Host SMTP')),
                ('email_port', models.PositiveIntegerField(blank=True, default=587, null=True, verbose_name='Puerto SMTP')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('email_host_user', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email SMTP User')),
                ('email_host_password', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Contraseña de Aplicación SMTP')),
                ('notif_event_creacion', models.BooleanField(default=True, verbose_name='Email al Crear Ticket')),
                ('notif_event_listo', models.BooleanField(default=True, verbose_name='Email al Estar Listo')),
                ('notif_event_entregado', models.BooleanField(default=False, verbose_name='Email al Entregar')),
                ('notif_whatsapp_activas', models.BooleanField(default=False, verbose_name='Activar WhatsApp')),
                ('notif_sms_activas', models.BooleanField(default=False, verbose_name='Activar SMS')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='HistorialSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(verbose_name='Fecha de Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('metodo', models.CharField(choices=[('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('EFECTIVO', 'Efectivo / Otro')], default='TRANSFERENCIA', max_length=20)),
                ('comprobante_codigo', models.CharField(blank=True, max_length=50, verbose_name='Código de Operación')),
                ('periodo_inicio', models.DateField(verbose_name='Inicio Periodo')),
                ('periodo_fin', models.DateField(verbose_name='Fin Periodo')),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_suscripciones', to='core.empresa')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial Suscripción',
                'verbose_name_plural': 'Historial Suscripciones',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('eliminado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la sede')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código Interno')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('horario_apertura', models.TimeField(verbose_name='Horario de apertura')),
                ('horario_cierre', models.TimeField(verbose_name='Horario de cierre')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
    ]
