# Generated by Django 5.2.9 on 2026-01-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ticket_dias_entrega',
            field=models.PositiveIntegerField(default=2, verbose_name='Días defecto para entrega'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ticket_mensaje_pie',
            field=models.TextField(blank=True, verbose_name='Mensaje al pie del ticket'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ticket_prefijo',
            field=models.CharField(default='TK-', max_length=10, verbose_name='Prefijo del Ticket'),
        ),
    ]
