# Generated by Django 5.2.9 on 2026-02-18 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_ticket_dias_entrega_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(verbose_name='Fecha de Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('metodo', models.CharField(choices=[('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('EFECTIVO', 'Efectivo / Otro')], default='TRANSFERENCIA', max_length=20)),
                ('comprobante_codigo', models.CharField(blank=True, max_length=50, verbose_name='Código de Operación')),
                ('periodo_inicio', models.DateField(verbose_name='Inicio Periodo')),
                ('periodo_fin', models.DateField(verbose_name='Fin Periodo')),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_suscripciones', to='core.empresa')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial Suscripción',
                'verbose_name_plural': 'Historial Suscripciones',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
