# Generated by Django 5.2.9 on 2026-02-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historialsuscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='ticket_dias_entrega',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='plan',
            field=models.CharField(choices=[('DEMO', 'Prueba de 7 días'), ('MENSUAL', 'Suscripción Mensual')], default='DEMO', max_length=20),
        ),
    ]
