# Generated by Django 5.2.9 on 2026-02-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_empresa_ticket_dias_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ticket_disclaimer',
            field=models.TextField(blank=True, verbose_name='Disclaimer del Ticket'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ticket_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_tickets/', verbose_name='Logo del Ticket'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ticket_servicios_descripcion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción Inline de Servicios'),
        ),
    ]
