# Generated by Django 5.2.9 on 2026-03-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresa_ticket_disclaimer_empresa_ticket_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', max_length=100, verbose_name='Host SMTP'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Contraseña de Aplicación SMTP'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_host_user',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email SMTP User'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_port',
            field=models.PositiveIntegerField(default=587, verbose_name='Puerto SMTP'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_use_tls',
            field=models.BooleanField(default=True, verbose_name='Usar TLS'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='notif_event_creacion',
            field=models.BooleanField(default=True, verbose_name='Email al Crear Ticket'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='notif_event_entregado',
            field=models.BooleanField(default=False, verbose_name='Email al Entregar'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='notif_event_listo',
            field=models.BooleanField(default=True, verbose_name='Email al Estar Listo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='notif_email_activas',
            field=models.BooleanField(default=False, verbose_name='Activar Notificaciones Email'),
        ),
    ]
