# Generated by Django 5.2.9 on 2026-03-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_empresa_email_host_empresa_email_host_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='email_port',
            field=models.PositiveIntegerField(blank=True, default=587, null=True, verbose_name='Puerto SMTP'),
        ),
    ]
