# Generated by Django 5.2.9 on 2026-01-15 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('eliminado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, max_length=50, verbose_name='Icono (React/Phosphor)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('eliminado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('multiplicador_precio', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Multiplicador de Precio')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Prenda',
                'verbose_name_plural': 'Prendas',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('eliminado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Servicio')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_cobro', models.CharField(choices=[('POR_UNIDAD', 'Precio Fijo por Unidad (Ej: Lavado de Alfombra m2)'), ('POR_KILO', 'Precio por Peso/Kilo (Ej: Lavado Diario)'), ('POR_PRENDA', 'Precio dependiente de la Prenda (Ej: Sastrería/Dry Clean)')], default='POR_UNIDAD', max_length=20, verbose_name='Tipo de Cobro')),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Base / Referencial')),
                ('tiempo_estimado', models.PositiveIntegerField(default=24, verbose_name='Tiempo Estimado (horas)')),
                ('requiere_prenda', models.BooleanField(default=False, verbose_name='¿Requiere especificar prenda?')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='servicios.categoriaservicio', verbose_name='Categoría')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='core.empresa', verbose_name='Empresa')),
                ('sedes', models.ManyToManyField(blank=True, related_name='servicios_disponibles', to='core.sede', verbose_name='Sedes donde está disponible')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('eliminado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Promoción')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('DESCUENTO_PORCENTAJE', 'Descuento en Porcentaje'), ('DESCUENTO_MONTO', 'Descuento en Monto Fijo'), ('COMBO', 'Combo de Servicios'), ('2X1', '2x1'), ('PRECIO_FIJO', 'Precio Fijo')], max_length=30, verbose_name='Tipo de Promoción')),
                ('valor_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor del Descuento')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('monto_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Mínimo de Compra')),
                ('cantidad_minima', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad Mínima de Items')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('usos_maximos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Usos Máximos')),
                ('usos_actuales', models.PositiveIntegerField(default=0, verbose_name='Usos Actuales')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='core.empresa', verbose_name='Empresa')),
                ('servicios', models.ManyToManyField(related_name='promociones', to='servicios.servicio', verbose_name='Servicios Incluidos')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PrecioPorPrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Final')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='core.empresa', verbose_name='Empresa')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_servicios', to='servicios.prenda', verbose_name='Prenda')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_prendas', to='servicios.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Precio por Prenda',
                'verbose_name_plural': 'Precios por Prenda',
                'ordering': ['servicio', 'prenda'],
            },
        ),
        migrations.CreateModel(
            name='TipoPrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('eliminado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, max_length=50, verbose_name='Icono')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Tipo de Prenda',
                'verbose_name_plural': 'Tipos de Prendas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='prenda',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prendas', to='servicios.tipoprenda', verbose_name='Tipo de Prenda'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['codigo'], name='servicios_s_codigo_7fecd1_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['categoria', 'disponible'], name='servicios_s_categor_d99ad1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicio',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='promocion',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='precioporprenda',
            unique_together={('servicio', 'prenda')},
        ),
        migrations.AlterUniqueTogether(
            name='tipoprenda',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='prenda',
            unique_together={('empresa', 'nombre', 'tipo')},
        ),
    ]
