# Generated by Django 5.2.9 on 2026-02-16 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_ticket_dias_entrega_and_more'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prenda',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='prenda',
            index=models.Index(fields=['tipo', 'nombre'], name='servicios_p_tipo_id_309cce_idx'),
        ),
    ]
