# Generated by Django 5.2.9 on 2026-01-18 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_ticket_dias_entrega_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='sedes_permitidas',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_asignados', to='core.sede', verbose_name='Sede Asignada'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador del Negocio'), ('CAJERO', 'Cajero / Ventas'), ('OPERARIO', 'Operario de Planta')], default='OPERARIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
