# Generated by Django 5.2.9 on 2026-01-19 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_ticket_dias_entrega_and_more'),
        ('usuarios', '0002_remove_perfilusuario_sedes_permitidas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={},
        ),
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='creado_en',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CAJERO', 'Cajero'), ('OPERARIO', 'Operario')], default='OPERARIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sede'),
        ),
    ]
