# Generated by Django 5.2.9 on 2026-02-16 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_ticket_dias_entrega_and_more'),
        ('usuarios', '0003_alter_perfilusuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='sedes_permitidas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_permitidos', to='core.sede', verbose_name='Sedes Adicionales'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_asignados', to='core.sede', verbose_name='Sede Principal'),
        ),
    ]
