# Generated by Django 5.2.9 on 2026-01-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tipo_entrega',
            field=models.CharField(choices=[('RECOJO', 'Recojo en Tienda'), ('DELIVERY', 'Delivery')], default='RECOJO', max_length=20, verbose_name='Tipo de Entrega'),
        ),
        migrations.AlterField(
            model_name='ticketitem',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad'),
        ),
    ]
