# Generated by Django 5.2.9 on 2026-03-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tracking_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
