# Generated by Django 5.2.9 on 2026-02-16 01:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_ticket_dias_entrega_and_more'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('EXPRESS', 'Express'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=20, verbose_name='Prioridad'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['email'], name='tickets_cli_email_24cc6c_idx'),
        ),
    ]
