# Generated by Django 5.2.9 on 2026-03-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_prioridad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='empleado_asignado',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='instrucciones_especiales',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='requiere_pago_anticipado',
        ),
        migrations.DeleteModel(
            name='ConfiguracionTicket',
        ),
    ]
