# Generated by Django 5.2.9 on 2026-03-27 04:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_populate_tracking_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tracking_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
